package genowl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RegionDepartement {

	public class Region {

		public String nom;
		public String[] deps;

		public Region (String n, String[] d){
			nom=n; deps=d;
		}

	}

	@SuppressWarnings("unused")
	public static void main(String[] args) {

		Map<String,List<String>> regions = new HashMap<String, List<String>>();

		String tmp = "ALSACE$BAS-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$CANTAL\n" + 
				"AUVERGNE$HAUTE-LOIRE\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BRETAGNE$COTES D'ARMOR\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIRET\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CORSE$CORSE DU SUD\n" + 
				"CORSE$HAUTE-CORSE\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$TERRITOIRE DE BELFORT\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUYANE$GUYANE\n" + 
				"ILE-DE-FRANCE$ESSONNE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE SAINT-DENIS\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$LOZERE\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LIMOUSIN$CORREZE\n" + 
				"LIMOUSIN$CREUSE\n" + 
				"LIMOUSIN$HAUTE VIENNE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$VOSGES\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$SOMME\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$HAUTES-ALPES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"REUNION$REUNION\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"ST PIERRE ET MIQUELON$SAINT-PIERRE ET MIQUELON";
		
		String tmp2 = "ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$BAS-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"ALSACE$HAUT-RHIN\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$DORDOGNE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$GIRONDE\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LANDES\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$LOT ET GARONNE\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AQUITAINE$PYRÉNÉES ATLANTIQUES\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$ALLIER\n" + 
				"AUVERGNE$CANTAL\n" + 
				"AUVERGNE$CANTAL\n" + 
				"AUVERGNE$CANTAL\n" + 
				"AUVERGNE$CANTAL\n" + 
				"AUVERGNE$CANTAL\n" + 
				"AUVERGNE$HAUTE-LOIRE\n" + 
				"AUVERGNE$HAUTE-LOIRE\n" + 
				"AUVERGNE$HAUTE-LOIRE\n" + 
				"AUVERGNE$HAUTE-LOIRE\n" + 
				"AUVERGNE$HAUTE-LOIRE\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"AUVERGNE$PUY DE DÔME\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$CÔTE D’OR\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$NIÈVRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$SAONE ET LOIRE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BOURGOGNE$YONNE\n" + 
				"BRETAGNE$COTES D'ARMOR\n" + 
				"BRETAGNE$COTES D'ARMOR\n" + 
				"BRETAGNE$COTES D'ARMOR\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$FINISTERE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$ILE ET VILAINE\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"BRETAGNE$MORBIHAN\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$CHER\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$EURE ET LOIR\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$INDRE ET LOIRE\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIR ET CHER\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CENTRE$LOIRET\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$ARDENNES\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$AUBE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$HAUTE-MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CHAMPAGNE-ARDENNE$MARNE\n" + 
				"CORSE$CORSE DU SUD\n" + 
				"CORSE$CORSE DU SUD\n" + 
				"CORSE$CORSE DU SUD\n" + 
				"CORSE$CORSE DU SUD\n" + 
				"CORSE$CORSE DU SUD\n" + 
				"CORSE$HAUTE-CORSE\n" + 
				"CORSE$HAUTE-CORSE\n" + 
				"CORSE$HAUTE-CORSE\n" + 
				"CORSE$HAUTE-CORSE\n" + 
				"CORSE$HAUTE-CORSE\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$DOUBS\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$HAUTE-SAONE\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$JURA\n" + 
				"FRANCHE-COMTE$TERRITOIRE DE BELFORT\n" + 
				"FRANCHE-COMTE$TERRITOIRE DE BELFORT\n" + 
				"FRANCHE-COMTE$TERRITOIRE DE BELFORT\n" + 
				"FRANCHE-COMTE$TERRITOIRE DE BELFORT\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUADELOUPE$GUADELOUPE\n" + 
				"GUYANE$GUYANE\n" + 
				"GUYANE$GUYANE\n" + 
				"GUYANE$GUYANE\n" + 
				"ILE-DE-FRANCE$ESSONNE\n" + 
				"ILE-DE-FRANCE$ESSONNE\n" + 
				"ILE-DE-FRANCE$ESSONNE\n" + 
				"ILE-DE-FRANCE$ESSONNE\n" + 
				"ILE-DE-FRANCE$ESSONNE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$HAUTS DE SEINE\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$PARIS\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE ET MARNE\n" + 
				"ILE-DE-FRANCE$SEINE SAINT-DENIS\n" + 
				"ILE-DE-FRANCE$SEINE SAINT-DENIS\n" + 
				"ILE-DE-FRANCE$SEINE SAINT-DENIS\n" + 
				"ILE-DE-FRANCE$SEINE SAINT-DENIS\n" + 
				"ILE-DE-FRANCE$SEINE SAINT-DENIS\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL D'OISE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$VAL DE MARNE\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"ILE-DE-FRANCE$YVELINES\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$AUDE\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$GARD\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$HERAULT\n" + 
				"LANGUEDOC-ROUSSILLON$LOZERE\n" + 
				"LANGUEDOC-ROUSSILLON$LOZERE\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LANGUEDOC-ROUSSILLON$PYRENEES ORIENTALES\n" + 
				"LIMOUSIN$CORREZE\n" + 
				"LIMOUSIN$CORREZE\n" + 
				"LIMOUSIN$CORREZE\n" + 
				"LIMOUSIN$CORREZE\n" + 
				"LIMOUSIN$CORREZE\n" + 
				"LIMOUSIN$CREUSE\n" + 
				"LIMOUSIN$CREUSE\n" + 
				"LIMOUSIN$HAUTE VIENNE\n" + 
				"LIMOUSIN$HAUTE VIENNE\n" + 
				"LIMOUSIN$HAUTE VIENNE\n" + 
				"LIMOUSIN$HAUTE VIENNE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEURTHE ET MOSELLE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MEUSE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$MOSELLE\n" + 
				"LORRAINE$VOSGES\n" + 
				"LORRAINE$VOSGES\n" + 
				"LORRAINE$VOSGES\n" + 
				"LORRAINE$VOSGES\n" + 
				"LORRAINE$VOSGES\n" + 
				"LORRAINE$VOSGES\n" + 
				"LORRAINE$VOSGES\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MARTINIQUE$MARTINIQUE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$ARIEGE\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$AVEYRON\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$GERS\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTE-GARONNE\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$HAUTES-PYRENEES\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$LOT\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"MIDI-PYRENEES$TARN-ET-GARONNE\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$NORD\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORD-PAS-DE-CALAIS$PAS-DE-CALAIS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$CALVADOS\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$MANCHE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (BASSE)$ORNE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$EURE\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"NORMANDIE (HAUTE)$SEINE-MARITIME\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$LOIRE-ATLANTIQUE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAINE-ET-LOIRE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$MAYENNE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$SARTHE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PAYS-DE-LA-LOIRE$VENDEE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$AISNE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$OISE\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"PICARDIE$SOMME\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$CHARENTE-MARITIME\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$DEUX-SEVRES\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"POITOU-CHARENTES$VIENNE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES DE HAUTE PROVENCE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$ALPES-MARITIMES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$BOUCHES DU RHONE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$HAUTES-ALPES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$HAUTES-ALPES\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAR\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"PROVENCE-ALPES-CÔTE D'AZUR$VAUCLUSE\n" + 
				"REUNION$REUNION\n" + 
				"REUNION$REUNION\n" + 
				"REUNION$REUNION\n" + 
				"REUNION$REUNION\n" + 
				"REUNION$REUNION\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$AIN\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$ARDECHE\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$DRÔME\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$HAUTE-SAVOIE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$ISERE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$LOIRE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$RHÔNE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"RHÔNE-ALPES$SAVOIE\n" + 
				"ST PIERRE ET MIQUELON$SAINT-PIERRE ET MIQUELON";

		for (String i : tmp.split("\n")){
			String r = i.split("\\$")[0];
			String d = i.split("\\$")[1];

			if (!regions.containsKey(r)){
				ArrayList<String> l = new ArrayList<String>();
				l.add(d);
				regions.put(r, l);
			}
			else
				regions.get(r).add(d);			
		}

		int itr=1,itd=1;
		
		Map<String, String> id = new HashMap<String, String>();
		
		for (String r : regions.keySet()){
			String toAdd = "###  http://www.musee.com/ontologies/musee.owl#R_"+itr+"\n\n";
			toAdd += ":R_"+itr+" rdf:type owl:NamedIndividual ;\n\n";

			toAdd += "          :aNom \""+r+"\" .\n\n\n\n";

			for (String j : regions.get(r)){
				toAdd += "###  http://www.musee.com/ontologies/musee.owl#D_"+itd+"\n\n";
				toAdd += ":D_"+itd+" rdf:type owl:NamedIndividual ;\n\n";
				toAdd += "    :estDépartementDeLaRégion :R_"+itr+" ;\n\n";
				toAdd += "    :aNomDépartement \""+j+"\" .\n\n\n\n";
				id.put(j,"D_"+itd);
				itd++;
			}

			System.out.println(toAdd);
			itr++;
		}
		
		/*for (String i : tmp2.split("\n")){
			System.out.println(id.get(i.split("\\$")[1]));
		}*/
	}

}
